version: '2'
services:
  vaccinetime:
    build: .
    volumes:
      - .:/usr/src/app
    links:
      - redis
    environment:
      REDIS_URL: redis://redis
      IN_DOCKER: 'true'
    stdin_open: true
    tty: true

  redis:
    image: redis
